service: halogen-backoffice-script
frameworkVersion: "3"

plugins:
  - serverless-esbuild
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  profile: scriptUser
  region: ap-southeast-1
  environment:
    bucketName: ${self:custom.bucketName}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:*
      Resource: "*"  

package:
  individually: true        

custom:
  customVariable1: Hello, World!
  bucketName: halogen-backoffice-script-serverlessdeploymentbuck-zvsxux6rd0xg

functions:
  createFile:
    handler: ./src/ts_lambdas/endpoints/createFile.handler
    events:
      - httpApi:
          path: /{hash}/{fileName}
          method: POST

  extractFiles:
    runtime: provided.al2023
    handler: ./src/go_lambdas/bin/extractFiles
    events:
      - http:
          path: /extractFiles
          method: GET
    package:
      artifact: ./src/go_lambdas/bin/extractFiles.zip