service: halogen-backoffice-script
frameworkVersion: "3"

plugins:
  - serverless-esbuild
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  profile: scriptUser
  region: ap-southeast-1
  environment:
    bucketName: ${self:custom.bucketName}
    tableName: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:*
        - dynamodb:*
      Resource: "*"  

package:
  individually: true

custom:
  customVariable1: Hello, World!
  bucketName: halogen-backoffice-script-serverlessdeploymentbuck-ylzwrvx10v52
  tableName: file-script

functions:
  createFile:
    handler: ./src/ts_lambdas/endpoints/createFile.handler
    events:
      - httpApi:
          path: /{hash}/{fileName}
          method: POST