service: halogen-backoffice-script
frameworkVersion: "3"

plugins:
  - serverless-esbuild
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  profile: scriptUser
  region: ap-southeast-1
  environment:
    bucketName: ${self:custom.bucketName}
    tableName: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:ListBucket
      Resource: arn:aws:s3:::backoffice-script
    - Effect: "Allow"
      Action:
        - s3:GetObject
        - s3:PutObject
        - s3:DeleteObject
      Resource: arn:aws:s3:::backoffice-script/*
    - Effect: "Allow"
      Action:
        - dynamodb:*
      Resource: "*"  

package:
  individually: true

custom:
  customVariable1: Hello, World!
  bucketName: backoffice-script
  tableName: file-script

functions:
  createFile:
    handler: ./src/ts_lambdas/endpoints/createFile.handler
    events:
      - httpApi:
          path: /{hash}/{fileName}
          method: POST